# ==========================================
# .github/workflows/deploy-lambda.yml
# NoKargo Technologies Inc. - Lambda CI/CD
# ==========================================

name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files for debug
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files recursively to confirm structure:"
          ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install production dependencies
        working-directory: nokargo-backend/lambda-functions/signupHandler
        run: npm install --production

      - name: Package Lambda function code
        working-directory: nokargo-backend/lambda-functions/signupHandler
        run: zip -r function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          inline: |
            aws lambda update-function-code \
              --function-name signupHandler \
              --zip-file fileb://function.zip

      - name: Confirm deployment
        run: echo "Lambda function deployed successfully."
