# ==========================================
# .github/workflows/deploy-lambda.yml
# NoKargo Technologies Inc. - Lambda CI/CD
# ==========================================

name: Deploy Lambda Function to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'nokargo-backend/lambda-functions/signupHandler/**'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust based on your Lambda runtime

      - name: Install production dependencies
        working-directory: nokargo-backend/lambda-functions/signupHandler
        run: npm install --production

      - name: Package Lambda function code
        working-directory: nokargo-backend/lambda-functions/signupHandler
        run: |
          zip -r function.zip . -x "*.git*" "node_modules/aws-sdk/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Adjust to your region

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name signupHandler \
            --zip-file fileb://nokargo-backend/lambda-functions/signupHandler/function.zip

      - name: Confirm deployment
        run: |
          aws lambda get-function-configuration \
            --function-name signupHandler
